Fix graphene-django version specification for Poetry 1.2
Only encountered this in CI, where poetry 1.2 started getting installed
(https://github.com/sjdemartini/graphene-django-permissions/actions/runs/3284716438/jobs/5411001549),
since originally I was using Poetry 1.1 locally:

```
poetry.core.constraints.version.exceptions.ParseConstraintError: Could not parse version constraint: ^3.0.0*
```

Poetry 1.2 (released August 2022) contained a backwards incompatible
change for `allow-preleases` logic, which led to this breakage (and
difference from 1.1). See
https://github.com/python-poetry/poetry/issues/3538#issuecomment-1270284506
for the new preferred approach.